# Generated by Django 4.1.1 on 2022-09-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stealMyBrain", "0002_employee_supervisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisor",
            name="email",
            field=models.EmailField(default="default@stealmybrain.com", max_length=50),
        ),
        migrations.AddField(
            model_name="supervisor", name="phone", field=models.IntegerField(null=True),
        ),
    ]
